/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_idcard_JDKCard */

#ifndef _Included_com_idcard_JDKCard
#define _Included_com_idcard_JDKCard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_idcard_JDKCard
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_idcard_JDKCard_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
